version: '3'

services:
  
  crm-web3-svc:
    build: ./
    hostname: crm-web3-svc
    restart: always
    env_file:
      - ./.dev.env
    networks:
      - postgres
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - /data/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./.dev.env
    networks:
      - postgres
  
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - ./.dev.env
    networks:
      - postgres

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis
        
  ipfs:
    image: lscr.io/linuxserver/ipfs
    container_name: ipfs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /data/ipfs:/config
    ports:
      - 80:80
      - 4001:4001
      - 5001:5001
      - 8080:8080
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
