version: '3.8'

services:

  app:
    container_name: crm-web3-svc
    build: 
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm-web3-svc
    ports:
      - 5678:5432
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - /data/pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8880:80
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - 6789:6379
    volumes:
      - /data/redis:/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8881:8081
    depends_on:
        - redis

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
  redis:
    driver: local
  ipfs:
    driver: local