version: '3'

services:

  crm-web3-svc:
    build: ./
    env_file:
      - ./.dev.env
    depends_on:
      - postgres
      - redis
      - ipfs
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm-web3-svc
    ports:
      - "5432:5432"
    restart: always
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - /data/pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: always

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
        - redis
    restart: always
        
  ipfs:
    container_name: ipfs
    image: lscr.io/linuxserver/ipfs
    volumes:
      - /data/ipfs:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 88:80
      - 4001:4001
      - 5050:5001
      - 8083:8080
    restart: always